### ISSUE TITLE
Error occurred when trying to display this plug-in: Unable to cast object type...

### ISSUE THREAD

**Issue by nexrm** [MscrmTools/DamSim.ViewTransferTool#10]
Error occurred when trying to display this plug-in: Unable to cast object type
'DamSim.ViewTransferTool.ViewTransferTool' to type 'XrmToolBox.Extensibility.PluginControlBase'.

This issue recently occurred.   
XrmToolBox Version 1.2018.3.21
ViewTranferTool Version: 1.2016.10.3

This issue appears to be on the Solution TransferTool as well.

Thank you and please advise.  We love using your tools

**Comment by MscrmTools** [comment]
Thank you for reporting it. The error is due to latest version of XrmToolBox. 
I will fix the plugin itself rather than updating XrmToolBox
