### ISSUE TITLE
Cannot transfer views from on prem to Online

### ISSUE THREAD

**Issue by StephaneSeguin** [MscrmTools/DamSim.ViewTransferTool#4]
When transferring a User view from On prem to Online it cannot match the users. 

Error cannot find user or team with name or ID.

**Comment by stephenedwardprice** [comment]
I believe when owned by a user, and going from on prem to online, this is an issue. If, however, the view is owned by a team, and you have a team with the same name in the target online instance, it will transfer.

**Comment by Eric370ZX** [comment]
Where can I find instructions how to use the View Transfer Tool?
