### ISSUE TITLE
Cannot transfer views of view type Lookup view

### ISSUE THREAD

**Issue by StephanSchulte** [MscrmTools/DamSim.ViewTransferTool#5]
As systemadministrator on trying to transfer a Lookup view i get the error message: "The view you tried to transfert already exists but you don't have read access to it. Get access to this view on the target organization to update it". What's the reason?
![image](https://cloud.githubusercontent.com/assets/25102662/21932570/817caa80-d9a1-11e6-8e10-dd24288a2944.png)

**Comment by MscrmTools** [comment]
Ok found! It is due to SDK enhancement that allows to change state using Update message. 
Fix is on its way!
