### ISSUE TITLE
object reference not set to an instance of an object

### ISSUE THREAD

**Issue by snice1981** [MscrmTools/DamSim.ViewTransferTool#6]
Hi,

I discovered a bug in the plugin. If I click on the Transfer Views button, I get an NullReferenceException. I have located the problem in the View.cs:
`if (owner != null && owner.LogicalName == "team" || owner.Id != targetCurrentUserId)`

Which should be changed to :
`if (owner != null && (owner.LogicalName == "team" || owner.Id != targetCurrentUserId))`

in order to work.

**Comment by MscrmTools** [comment]
thank you for the feedback, I will update it

**Comment by nzhome** [comment]
when can you release a new version of the plugin?  this plugin doesn't work at all until this is fixed.
