### ISSUE TITLE
Plugin description says Dashboard Transfer Tool

### ISSUE THREAD

**Issue by rappen** [MscrmTools/DamSim.ViewTransferTool#7]
It looks like the plugin description is copied from Dashboard Transfer Tool, but this apparently transfers Views...

![image](https://cloud.githubusercontent.com/assets/2572253/22058335/d5eb9b56-dd68-11e6-8fda-46dd2dceb64a.png)

![image](https://cloud.githubusercontent.com/assets/2572253/22058299/bdfc30b4-dd68-11e6-8cfa-fbc5ce8e72ee.png)

**Comment by MscrmTools** [comment]
O_o... I can't see this on my XTB with the same plugin version

**Comment by MscrmTools** [comment]
I guess it was a try of mine that I must have shipped by error.
This does not exist anymore
