### ISSUE TITLE
Enhancement Request - Consider including translations in transfer

### ISSUE THREAD

**Issue by Lafil** [MscrmTools/DamSim.ViewTransferTool#9]
Hi, this is a wonderful tool!
We operate in an environment that supports English and French, English being the base language.
I notice that when I transfer views via the tool, it does not include the French names for the views.
It is possible to include translatated view names in a future release of this tool?
Thanks!

**Comment by Lafil** [comment]
Hurray, thank you!

**Comment by MscrmTools** [comment]
You're welcome and sorry it took so long to implement.
I'm in the process of reviewing all my tools issues :)
